server:
  port: 8000

spring:
  profiles:
    active: dev   #激活的配置文件
  jackson:
    time-zone: GMT+8  #设置jackson时区
  data:
    redis:
      repositories:
        enabled: false  #关闭redis repository的支持
  freemarker:
    check-template-location: false  #关闭freemarker检查模板位置

  #redis相关配置
  redis:
    database: 0
    #host: 192.168.2.75
    host: 59.110.154.99
    port: 6379
    password:
    timeout: 5000

  #jpa相关配置
  jpa:
    properties:
      hibernate:
        # create 每次运行该程序，没有表格会新建表格，表内有数据会清空
        # create-drop 每次程序结束的时候会清空表
        # update 每次运行程序，没有表格会新建表格，表内有数据不会清空，只会更新
        # validate 运行程序会校验数据与数据库的字段类型是否相同，不同会报错
        # none 每次启动与关闭应用不对数据表做任何操作
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true


#登录图形验证码有效时间（单位：分钟）
loginCode:
  expiration: 2

#密码加密传输，前端公钥加密、后端私钥解密
rsa:
  private_key: MIIBUwIBADANBgkqhkiG9w0BAQEFAASCAT0wggE5AgEAAkEA0vfvyTdGJkdbHkB8mp0f3FE0GYP3AYPaJF7jUd1M0XxFSE2ceK3k2kw20YvQ09NJKk+OMjWQl9WitG9pB6tSCQIDAQABAkA2SimBrWC2/wvauBuYqjCFwLvYiRYqZKThUS3MZlebXJiLB+Ue/gUifAAKIg1avttUZsHBHrop4qfJCwAI0+YRAiEA+W3NK/RaXtnRqmoUUkb59zsZUBLpvZgQPfj1MhyHDz0CIQDYhsAhPJ3mgS64NbUZmGWuuNKp5coY2GIj/zYDMJp6vQIgUueLFXv/eZ1ekgz2Oi67MNCk5jeTF2BurZqNLR3MSmUCIFT3Q6uHMtsB9Eha4u7hS31tj1UWE+D+ADzp59MGnoftAiBeHT7gDMuqeJHPL4b+kC+gzV4FGTfhR9q3tTbklZkD2A==