#开发环境配置

#配置数据源
spring:
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://localhost:3306/eladmin?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: root
      password: Gepoint
      #初始连接数
      initial-size: 5
      #最小连接数
      min-idle: 10
      #最大连接数
      max-active: 20
      #连接超时时间
      max-wait: 5000
      #连接有效性检测时间
      time-between-eviction-runs-millis: 60000
      #在连接池中最小生存时间
      min-evictable-idle-time-millis: 300000
      #在连接池中的最大生存时间
      max-evictable-idle-time-millis: 900000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #检测连接是否有效
      validation-query: select 1
      #配置监控统计
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
      filter:
        stat:
          enabled: true
          #记录慢sql
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  security:
    user:
      name: user
      password: user

#jwt相关配置
jwt:
  header: Authorization
  #令牌前缀
  token-start-with: Bearer
  #必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  #令牌过期时间（单位：毫秒），默认4小时
  token-validity-in-millisecond: 14400000
  #在线用户key
  online-key: online-token-
  #验证码
  code-key: code-key-
  #token续期检查时间（单位：毫秒），默认30分钟。在token即将过期的时间内用户操作了，则给用户的token续期时间
  detect: 1800000
  #续期时间（单位：毫秒），默认1小时
  renew: 3600000